-- StudyPace D 담당: 공모전 검색·추천·개인화 기반 스키마
-- Supabase SQL Editor 또는 마이그레이션 도구에서 한 번 실행한다.

create extension if not exists pgcrypto;
create extension if not exists vector;

create table if not exists public.contests (
    id uuid primary key default gen_random_uuid(),
    source text not null,
    source_id text not null,
    title text not null,
    host text not null,
    fields text[] not null default '{}',
    eligibility_text text,
    start_date date,
    deadline date not null,
    status text not null default 'open'
        check (status in ('upcoming', 'open', 'closed', 'unknown')),
    source_url text not null,
    official_url text,
    summary text,
    raw_text text,
    content_hash text not null,
    collected_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source, source_id)
);

create index if not exists contests_deadline_idx
    on public.contests (deadline);
create index if not exists contests_status_deadline_idx
    on public.contests (status, deadline);
create index if not exists contests_fields_gin_idx
    on public.contests using gin (fields);

create table if not exists public.contest_embeddings (
    contest_id uuid primary key references public.contests(id) on delete cascade,
    embedding vector(1536),
    content_hash text not null,
    index_status text not null default 'pending'
        check (index_status in ('pending', 'indexed', 'failed')),
    indexed_at timestamptz,
    error_message text,
    updated_at timestamptz not null default now()
);

create index if not exists contest_embeddings_hnsw_idx
    on public.contest_embeddings
    using hnsw (embedding vector_cosine_ops)
    where embedding is not null;

create table if not exists public.preparation_time_standards (
    id bigint generated by default as identity primary key,
    field text not null unique,
    category_group text not null,
    standard_hours numeric(7, 2) not null check (standard_hours > 0),
    sample_size integer not null default 0 check (sample_size >= 0),
    basis text not null,
    active boolean not null default true,
    updated_at timestamptz not null default now()
);

create table if not exists public.contest_recommendations (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    contest_id uuid not null references public.contests(id) on delete cascade,
    recommendation_week date not null,
    similarity numeric(6, 5) not null check (similarity between 0 and 1),
    deadline_score numeric(6, 5) not null check (deadline_score between 0 and 1),
    eligibility_score numeric(6, 5) not null check (eligibility_score between 0 and 1),
    rerank_score numeric(6, 5) not null check (rerank_score between 0 and 1),
    reason text,
    matching_tags text[] not null default '{}',
    created_at timestamptz not null default now(),
    unique (user_id, recommendation_week, contest_id)
);

create index if not exists contest_recommendations_user_week_idx
    on public.contest_recommendations (user_id, recommendation_week desc);

create table if not exists public.contest_feedback (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    contest_id uuid not null references public.contests(id) on delete cascade,
    rating text not null check (rating in ('helpful', 'not_relevant')),
    reason text check (
        reason is null or reason in ('field', 'difficulty', 'deadline')
    ),
    similarity numeric(6, 5) check (similarity between 0 and 1),
    rerank_score numeric(6, 5) check (rerank_score between 0 and 1),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, contest_id)
);

create table if not exists public.user_memories (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    memory_type text not null check (
        memory_type in (
            'preferred_study_time',
            'effort_deviation',
            'interest_tags',
            'rejected_recommendations',
            'four_week_completion_rate'
        )
    ),
    memory_key text not null default 'default',
    value jsonb not null,
    basis text not null,
    updated_at timestamptz not null default now(),
    expires_at timestamptz not null default (now() + interval '12 months'),
    unique (user_id, memory_type, memory_key)
);

create index if not exists user_memories_user_updated_idx
    on public.user_memories (user_id, updated_at desc);
create index if not exists user_memories_expiry_idx
    on public.user_memories (expires_at);

create table if not exists public.batch_runs (
    id uuid primary key default gen_random_uuid(),
    job_name text not null,
    source text,
    status text not null check (status in ('running', 'success', 'partial', 'failed')),
    collected_count integer not null default 0,
    indexed_count integer not null default 0,
    failed_count integer not null default 0,
    error_message text,
    started_at timestamptz not null default now(),
    finished_at timestamptz
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists contests_set_updated_at on public.contests;
create trigger contests_set_updated_at
before update on public.contests
for each row execute function public.set_updated_at();

drop trigger if exists contest_feedback_set_updated_at on public.contest_feedback;
create trigger contest_feedback_set_updated_at
before update on public.contest_feedback
for each row execute function public.set_updated_at();

drop trigger if exists user_memories_set_updated_at on public.user_memories;
create trigger user_memories_set_updated_at
before update on public.user_memories
for each row execute function public.set_updated_at();

alter table public.contests enable row level security;
alter table public.contest_embeddings enable row level security;
alter table public.preparation_time_standards enable row level security;
alter table public.contest_recommendations enable row level security;
alter table public.contest_feedback enable row level security;
alter table public.user_memories enable row level security;
alter table public.batch_runs enable row level security;

drop policy if exists "public can read active contests" on public.contests;
create policy "public can read active contests"
on public.contests for select
using (status in ('upcoming', 'open') and deadline >= current_date);

drop policy if exists "public can read preparation standards" on public.preparation_time_standards;
create policy "public can read preparation standards"
on public.preparation_time_standards for select
using (active = true);

drop policy if exists "users can read own recommendations" on public.contest_recommendations;
create policy "users can read own recommendations"
on public.contest_recommendations for select
using (auth.uid() = user_id);

drop policy if exists "users can read own feedback" on public.contest_feedback;
create policy "users can read own feedback"
on public.contest_feedback for select
using (auth.uid() = user_id);

drop policy if exists "users can insert own feedback" on public.contest_feedback;
create policy "users can insert own feedback"
on public.contest_feedback for insert
with check (auth.uid() = user_id);

drop policy if exists "users can update own feedback" on public.contest_feedback;
create policy "users can update own feedback"
on public.contest_feedback for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "users can delete own feedback" on public.contest_feedback;
create policy "users can delete own feedback"
on public.contest_feedback for delete
using (auth.uid() = user_id);

drop policy if exists "users can read own memories" on public.user_memories;
create policy "users can read own memories"
on public.user_memories for select
using (auth.uid() = user_id);

drop policy if exists "users can delete own memories" on public.user_memories;
create policy "users can delete own memories"
on public.user_memories for delete
using (auth.uid() = user_id);

-- contest_embeddings, batch_runs 및 user_memories 쓰기는 Service Role 전용이다.
-- Service Role은 RLS를 우회하며 브라우저에 노출하면 안 된다.
