import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role;
create schema auth; create table auth.users(id uuid primary key);
create table public.users(id bigserial primary key,user_id uuid references auth.users(id) on delete cascade,email text,nickname text,agree_privacy boolean,agree_ai_notice boolean,agree_marketing boolean,agreed_at timestamptz);
create table study_plans(id bigserial primary key,user_id uuid not null references auth.users(id) on delete cascade);
create table plan_blocks(id bigserial primary key,plan_id bigint references study_plans(id) on delete cascade);
create table notification_logs(id bigserial primary key,user_id uuid not null references auth.users(id) on delete cascade,block_id bigint references plan_blocks(id) on delete cascade);
create table study_sessions(id bigserial primary key,user_id uuid not null references auth.users(id) on delete cascade);
create table user_memories(id bigserial primary key,user_id uuid not null references auth.users(id) on delete cascade);
create table ai_call_logs(id bigserial primary key,user_id uuid references auth.users(id) on delete set null);
create schema cron;create table cron.job(jobname text,schedule text,command text,active boolean);
create function cron.schedule(text,text,text) returns bigint language sql as $$insert into cron.job values($1,$2,$3,true);select 1::bigint;$$;`);
const sql=fs.readFileSync(new URL('../../backend/migrations/010_withdrawal_retention.sql', import.meta.url),'utf8')
  .replace(/^create extension if not exists pg_cron.*$/m,'').replace(/^grant usage on schema cron to postgres;$/m,'');
await db.exec(sql);
const scalar=async sql=>(await db.query(sql)).rows[0].v;
const a='00000000-0000-0000-0000-000000000001',b='00000000-0000-0000-0000-000000000002';
await db.exec(`insert into auth.users values('${a}'),('${b}');
insert into public.users(user_id,email,nickname,agree_privacy,agree_ai_notice,agree_marketing,agreed_at) values('${a}','a@example.com','A',true,true,false,now()),('${b}','b@example.com','B',true,true,false,now());
insert into study_plans(user_id) values('${a}'),('${b}');insert into plan_blocks(plan_id) values(1),(2);
insert into notification_logs(user_id,block_id) values('${a}',1),('${b}',2),('${a}',null);
insert into study_sessions(user_id) values('${a}'),('${b}');insert into user_memories(user_id) values('${a}'),('${b}');
insert into ai_call_logs(user_id) values('${a}'),('${b}');`);
assert.equal(await scalar('select public.withdrawal_retention_ready() as v'),true);
await db.exec("alter table private.withdrawn_profiles add constraint test_failure check(email <> 'a@example.com')");
await assert.rejects(db.exec(`delete from auth.users where id='${a}'`));
assert.equal(await scalar('select count(*)::int as v from auth.users'),2);
assert.equal(await scalar('select count(*)::int as v from study_plans'),2);
await db.exec('alter table private.withdrawn_profiles drop constraint test_failure');
await db.exec(`delete from auth.users where id='${a}'`);
for(const table of ['auth.users','public.users','study_plans','plan_blocks','notification_logs','study_sessions','user_memories','ai_call_logs'])assert.equal(await scalar(`select count(*)::int as v from ${table}`),1,table);
const row=(await db.query('select * from private.withdrawn_profiles')).rows[0];assert.equal(row.email,'a@example.com');
for(const key of ['password_hash','auth_id','user_id','access_token','refresh_token'])assert.equal(key in row,false,key);
assert.equal(await scalar("select expires_at = ((withdrawn_at at time zone 'UTC' + interval '1 year') at time zone 'UTC') as v from private.withdrawn_profiles"),true);
for(const role of ['anon','authenticated','service_role']){await db.exec(`set role ${role}`);await assert.rejects(db.query('select * from private.withdrawn_profiles'));if(role==='service_role')assert.equal(await scalar('select public.withdrawal_retention_ready() as v'),true);else await assert.rejects(db.query('select public.withdrawal_retention_ready()'));await db.exec('reset role');}
assert.equal(await scalar('select private.purge_expired_profiles()::int as v'),0);
await db.exec("update private.withdrawn_profiles set withdrawn_at=now()-interval '2 years',expires_at=now()-interval '1 day'");assert.equal(await scalar('select private.purge_expired_profiles()::int as v'),1);
await db.exec('update cron.job set active=false');assert.equal(await scalar('select public.withdrawal_retention_ready() as v'),false);
await db.exec('update cron.job set active=true;alter table auth.users disable trigger archive_profile_before_auth_delete');assert.equal(await scalar('select public.withdrawal_retention_ready() as v'),false);
assert.equal(await scalar("select ('2024-02-29 12:00:00+00'::timestamptz at time zone 'UTC' + interval '1 year')::date = date '2025-02-28' as v"),true);
console.log('PASS: rollback, owner isolation, dependent deletion, profile allowlist, calendar-year expiry, role restrictions, purge, cron/trigger readiness. Cron execution mocked.');await db.close();
